
kafka.bootstrap-servers=localhost:9092

# Producer
kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

# topics
kafka.sensor-event-topic=telemetry.sensors.v1
kafka.hub-event-topic=telemetry.hubs.v1

grpc.server.port=59091
#grpc.server.reflection-service-enabled=true
#grpc.client.collector.address=static://localhost:9090
#grpc.client.collector.enableKeepAlive=true
#grpc.client.collector.keepAliveWithoutCalls=true
#grpc.client.collector.negotiationType=plaintext
