aggregator.bootstrap-servers=localhost:9092

# Producer
aggregator.key-serializer=org.apache.kafka.common.serialization.StringSerializer
aggregator.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

# Consumer
aggregator.client-id=aggregator-client-1
aggregator.group-id=aggregator-group
aggregator.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.value-deserializer=ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
aggregator.max-poll-records-config=100
aggregator.fetch-max-bytes-config=3072000
aggregator.max-partition-fetch-bytes-config=307200

# topics
aggregator.sensor-event-topic=telemetry.sensors.v1
aggregator.hub-event-topic=telemetry.hubs.v1
aggregator.snapshot-topic=telemetry.snapshots.v1