analyzer.bootstrap-servers=localhost:9092
grpc.server.port=9094

# Producer
analyzer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
analyzer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

# Consumer
analyzer.client-id-hub=analyzer-hub-client-1
analyzer.group-id-hub=analyzer-hub-group
analyzer.client-id-snapshot=analyzer-snapshot-client-1
analyzer.group-id-snapshot=analyzer-snapshot-group
analyzer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
analyzer.hub-value-deserializer=ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
analyzer.snapshot-value-deserializer=ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
analyzer.max-poll-records-config=100
analyzer.fetch-max-bytes-config=3072000
analyzer.max-partition-fetch-bytes-config=307200

# topics
analyzer.hub-event-topic=telemetry.hubs.v1
analyzer.snapshot-topic=telemetry.snapshots.v1

# hub-router
grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enable-keep-alive=true
grpc.client.hub-router.keep-alive-without-calls=true
grpc.client.hub-router.negotiation-type=plaintext


# database
server.port=9096

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/smart-home
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=dbuser
spring.datasource.password=12345